services:
  chatty-api-gateway:
    ports:
      - 3001:3001
    build:
      context: .
    depends_on:
      chatty-api-gateway-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  chatty-api-gateway-db:
    image: postgres:17
    ports:
      - 5433:5432
    restart: always
    volumes:
      - chatty-api-gateway-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=chatty_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]

  rabbitmq:
    image: rabbitmq:4.0.5-management
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq/

volumes:
  chatty-api-gateway-db:
  rabbitmq:
