version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    ports:
      - 5433:5432
    restart: always
    volumes:
      - db:/data/postgres
    networks:
      - chatty
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=chatty_db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - chatty

networks:
  chatty:
    driver: bridge

volumes:
  db:
  pgadmin-data: