services:
  chatty-api-gateway:
    ports:
      - 3000:3000
    build:
      context: .
    depends_on:
      chatty-api-gateway-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  chatty-api-gateway-db:
    image: postgres:17
    ports:
      - 5432:5432
    restart: always
    volumes:
      - chatty-api-gateway-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chatty_api_gateway
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]

volumes:
  chatty-api-gateway-db:
